#server:
#  port: 8090
#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/test
#    username: root
#    password: dyc191909
server:
  port: 8086
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/library

    username: root
    password: dyc191909
